version: '3'
services:
  reporter:
    build:
      context: $PWD
      dockerfile: $PWD/Docker/flask/Dockerfile
    image: reporter-flask:0.0
    container_name: flask-reporter
    hostname: flask
    restart: always
    volumes: 
      - $PWD/react-reporter:/mnt/react-reporter
      - $PWD/flask-receiver:/mnt/flask-receiver
      - $PWD/report:/mnt/report
    ports: 
      - 8994:5000
    tty: true
